# Generated by Django 2.1.5 on 2019-03-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credit',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
