# Generated by Django 2.1.5 on 2019-03-06 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyingApp', '0002_subject_credit'),
    ]

    operations = [

        migrations.RenameModel('Subject', 'SubjectBachelor'),

        migrations.CreateModel(
            name='SubjectMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('credit', models.CharField(max_length=5)),
                ('form', models.IntegerField(choices=[(0, 'Магістратура (системи штучного інтелекту)'), (1, 'Магістратура (машинне і глибоке навчання)')], default=0)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='StudyingApp.SubjectType')),
            ],
        ),
        migrations.RemoveField(
            model_name='SubjectBachelor',
            name='form',
        ),

    ]
