# Generated by Django 2.1.5 on 2019-03-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyingApp', '0003_auto_20190307_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectbachelor',
            options={'ordering': ['-semester', 'type']},
        ),
    ]
