# Generated by Django 2.1.2 on 2019-04-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyingApp', '0004_auto_20190308_0020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmaster',
            options={'ordering': ['-form', '-semester', 'type']},
        ),
    ]
