# Generated by Django 2.1.5 on 2019-02-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='building',
            field=models.CharField(max_length=255, verbose_name='building'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='building_en',
            field=models.CharField(max_length=255, verbose_name='building_en'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='location',
            field=models.CharField(max_length=255, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='location_en',
            field=models.CharField(max_length=255, verbose_name='location_en'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='site',
            field=models.CharField(max_length=255, verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='site_en',
            field=models.CharField(max_length=255, verbose_name='site_en'),
        ),
    ]
