# Generated by Django 2.1.5 on 2019-02-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20190215_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=128)),
                ('app_topic', models.CharField(blank=True, max_length=128)),
                ('app_topic_en', models.CharField(blank=True, max_length=128)),
                ('text', models.TextField()),
                ('text_en', models.TextField()),
            ],
        ),
    ]
