# Generated by Django 2.1.5 on 2019-02-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_appcontent'),
    ]

    operations = [
        migrations.RenameModel('AppContent', 'PageContent')
    ]
