# Generated by Django 2.1.5 on 2019-02-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20190223_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='pagecontent',
            old_name='app_name',
            new_name='page_name',
        ),
        migrations.RenameField(
            model_name='pagecontent',
            old_name='app_topic',
            new_name='page_topic',
        ),
        migrations.RenameField(
            model_name='pagecontent',
            old_name='app_topic_en',
            new_name='page_topic_en',
        )
    ]
