# Generated by Django 2.1.5 on 2019-02-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20190223_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='page_topic',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page_topic_en',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
