# Generated by Django 2.1.5 on 2019-02-23 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_auto_20190223_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='page_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.Page'),
        ),
    ]
