# Generated by Django 2.1.5 on 2019-02-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_auto_20190223_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagecontent',
            old_name='page_name',
            new_name='page',
        ),
    ]
