# Generated by Django 2.1.5 on 2019-02-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_auto_20190223_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='special_page',
            field=models.BooleanField(default=False),
        ),
    ]
