# Generated by Django 2.1.5 on 2019-02-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_page_special_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='admission_location',
            field=models.CharField(default='', help_text='for entrants', max_length=255, verbose_name='admission_location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='admission_location_en',
            field=models.CharField(default='', help_text='for entrants', max_length=255, verbose_name='admission_location'),
            preserve_default=False,
        ),
    ]
