# Generated by Django 2.1.5 on 2019-02-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_auto_20190225_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='index',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'about department'), (2, 'studying'), (3, 'students achievements'), (4, 'other')], default=0),
        ),
    ]
