# Generated by Django 2.1.2 on 2019-04-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_page_page_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='index',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'about department'), (2, 'studying'), (3, 'students achievements'), (4, 'other'), (5, 'science')], default=0),
        ),
    ]
