# Generated by Django 2.1.5 on 2019-03-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Best',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pictures/stud/%Y/%m/%D/')),
                ('image_name', models.CharField(blank=True, default='', max_length=255)),
                ('course', models.CharField(default='', max_length=255)),
                ('student', models.TextField()),
            ],
        ),
    ]
