# Generated by Django 2.1.5 on 2019-03-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudAchievApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best',
            name='image',
            field=models.ImageField(blank=True, upload_to='pictures/stud/%Y/%m/%D/'),
        ),
    ]
