# Generated by Django 2.1.5 on 2019-03-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudAchievApp', '0002_auto_20190305_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best',
            name='image',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/%D/'),
        ),
    ]
