# Generated by Django 2.1.3 on 2018-11-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%D/')),
                ('role', models.CharField(max_length=255, null=True)),
                ('orc_id', models.CharField(max_length=40, null=True)),
                ('field_of_work', models.CharField(max_length=255, null=True)),
                ('science_interests', models.CharField(max_length=255, null=True)),
                ('science_researches', models.CharField(max_length=500, null=True)),
                ('interests', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
