# Generated by Django 2.1.5 on 2019-02-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Прізвище Ім'я По-батькові", max_length=255)),
                ('full_name_en', models.CharField(help_text='Last name Name Surname', max_length=255)),
                ('photo', models.ImageField(blank=True, max_length=255, upload_to='pictures/%Y/%m/%D/')),
                ('role', models.CharField(max_length=255)),
                ('role_en', models.CharField(max_length=255)),
                ('field_of_work', models.CharField(blank=True, max_length=255)),
                ('field_of_work_en', models.CharField(blank=True, max_length=255)),
                ('science_interests', models.CharField(blank=True, max_length=255)),
                ('science_interests_en', models.CharField(blank=True, max_length=255)),
                ('science_researches', models.CharField(blank=True, max_length=500)),
                ('science_researches_en', models.CharField(blank=True, max_length=500)),
                ('interests', models.TextField(blank=True, max_length=500)),
                ('interests_en', models.TextField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('scopus_id', models.IntegerField(default=0)),
                ('scopus_orcid', models.CharField(blank=True, default=' ', max_length=100)),
                ('scopus_hindex', models.IntegerField(default='0')),
                ('scopus_documents', models.IntegerField(default='0')),
                ('scopus_citations', models.IntegerField(default='0')),
            ],
        ),
    ]
