# Generated by Django 2.1.3 on 2018-11-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%D/'),
        ),
    ]
