# Generated by Django 2.1.5 on 2019-02-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='field_of_work',
            new_name='academic_site',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='field_of_work_en',
        ),
        migrations.AddField(
            model_name='teacher',
            name='scientific_rank',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='scientific_rank_en',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role_en',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='science_interests',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='science_interests_en',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='science_researches',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='science_researches_en',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
