# Generated by Django 2.1.5 on 2019-02-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersApp', '0002_auto_20190208_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='scientific_rank',
            field=models.CharField(default='', max_length=255),
        ),
    ]
