# Generated by Django 2.1.3 on 2018-11-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersApp', '0002_teacher_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='field_of_work',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='science_interests',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='science_researches',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='interests',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='orc_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
