# Generated by Django 2.0.3 on 2018-11-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersApp', '0003_auto_20181118_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='scopus_citations',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='scopus_documents',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='scopus_hindex',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='scopus_id',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='scopus_orcid',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
