# Generated by Django 2.1.5 on 2019-02-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersApp', '0004_auto_20190209_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='academic_site',
            field=models.URLField(blank=True, max_length=255, verbose_name='academic_site'),
        ),
    ]
