# Generated by Django 2.0.3 on 2018-11-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersApp', '0005_remove_teacher_orc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='scopus_id',
            field=models.IntegerField(default=0),
        ),
    ]
