# Generated by Django 2.1.5 on 2019-02-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CooperationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='coop_site',
            field=models.CharField(blank=True, max_length=255, verbose_name='coop_site'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='name_en',
            field=models.TextField(verbose_name='name_en'),
        ),
    ]
