# Generated by Django 2.1.5 on 2019-02-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CooperationApp', '0002_auto_20190209_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='coop_site',
            field=models.URLField(blank=True, max_length=255, verbose_name='coop_site'),
        ),
    ]
