# Generated by Django 2.1.5 on 2019-02-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='index',
            field=models.IntegerField(choices=[(0, 'other'), (1, 'phone number'), (2, 'email'), (3, 'social network'), (4, 'post index')], default=0),
        ),
    ]
