# Generated by Django 2.1.5 on 2019-02-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactApp', '0002_contact_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='selection_committee',
            field=models.BooleanField(default=False),
        ),
    ]
