# Generated by Django 2.1.5 on 2019-02-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('description_en', models.CharField(max_length=1000)),
                ('site', models.URLField(blank=True)),
                ('icon', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%D/')),
            ],
        ),
    ]
