# Generated by Django 2.1.5 on 2019-02-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartnerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description_en',
            field=models.TextField(),
        ),
    ]
