# Generated by Django 2.1.5 on 2019-02-06 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('topic_en', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('short_description_en', models.TextField(blank=True)),
                ('post', models.TextField()),
                ('post_en', models.TextField()),
                ('data_post', models.DateField(default=datetime.date.today)),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%D/')),
            ],
        ),
    ]
