# Generated by Django 2.1.3 on 2018-12-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('post', models.TextField()),
                ('data_post', models.DateField(null=True)),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%D/')),
            ],
        ),
    ]
