# Generated by Django 2.1.5 on 2019-02-09 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0003_auto_20190209_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, help_text='Use ImagesForm if you want to add more than one image', max_length=255, null=True, upload_to='pictures/%Y/%m/%D/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='', upload_to='pictures/%Y/%m/%D/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='data_post',
            field=models.DateField(default=datetime.date.today, verbose_name='data_post'),
        ),
        migrations.AlterField(
            model_name='news',
            name='post',
            field=models.TextField(verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='news',
            name='post_en',
            field=models.TextField(verbose_name='post_en'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=500, verbose_name='short_description_en'),
        ),
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.CharField(max_length=255, verbose_name='topic'),
        ),
        migrations.AlterField(
            model_name='news',
            name='topic_en',
            field=models.CharField(max_length=255, verbose_name='topic_en'),
        ),
    ]
