# Generated by Django 2.1.5 on 2019-02-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0004_auto_20190209_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_uk', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, to='NewsApp.Tag'),
        ),
    ]
