# Generated by Django 2.1.5 on 2019-02-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0005_auto_20190215_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
