# Generated by Django 2.1.5 on 2019-03-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0006_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['data_post']},
        ),
    ]
